version: '3.7'
services:
  composer:
    image: composer:2.6
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: never
  php73:
    image: php:7.3-cli
    volumes:
      - .:/app
    working_dir: /app
    restart: never
  phpunit73:
    image: php:7.3-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
