version: '3.7'
services:
  composer:
    image: composer:2.2
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: never
  php55:
    image: php:5.5-cli
    volumes:
      - .:/app
    working_dir: /app
    restart: never
  php70:
    image: php:7.0-cli
    volumes:
      - .:/app
    working_dir: /app
    restart: never
  phpunit55:
    image: php:5.5-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  phpunit70:
    image: php:7.0-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
