version: 2.1

jobs:
  install-composer-dependencies:
    steps:
      - checkout
      - run: docker-compose run composer install
  test-php55:
    steps:
      - checkout
      - run: docker-compose run phpunit55 test/unit
  test-php70:
    steps:
      - checkout
      - run: docker-compose run phpunit70 test/unit      

workflows:
  build_and_test:
    - install-composer-dependencies
    - test-php55
    - test-php70