version: 2.1

jobs:
  test-php55:
    machine:  
      image: ubuntu-2004:202107-02    
    steps:
      - checkout
      - run: docker-compose run composer install
      - run: docker-compose run phpunit55 test/unit
  test-php70:
    machine:  
      image: ubuntu-2004:202107-02    
    steps:
      - checkout
      - run: docker-compose run composer install
      - run: docker-compose run phpunit70 test/unit      

workflows:
  build_and_test:
    jobs:    
      - test-php55
      - test-php70