version: 2.1

jobs:
  linting:
    docker:
      - image: php:7.0-cli
    steps:
      - checkout
      - run: php composer.phar install
      - run: ./vendor/bin/phpcs ./src
  test-php55:
    machine:  
      image: ubuntu-2004:202107-02    
    steps:
      - checkout
      - run: docker-compose run composer install
      - run: docker-compose run phpunit55 tests/unit
  test-php70:
    machine:  
      image: php:7.0-cli
    steps:
      - checkout
      - run: php composer.phar install
      - run: ./vendor/bin/phpunit tests/unit      

workflows:
  build_and_test:
    jobs:    
      - linting
      - test-php55:
          requires:
            - linting
      - test-php70:
          requires:
            - linting      